id = "nordppuccin-theme"
name = "Nordppuccin"
version = "0.0.2"
schema_version = 1
authors = ["franqong"]
description = "A hybrid theme combining Nord's cold icy aesthetic with Catppuccin's pastel syntax."
repository = "https://github.com/franqong/nordppuccin-zed"